services:

  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.3-fpm
    container_name: search_zip_php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
      REDIS_HOST: redis
      DB_HOST: mysql
      DB_USER: devkraken
      DB_PASSWORD: DevKraken
      DB_NAME: search_zip
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: search_zip_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: search_zip_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: search_zip_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: DevKraken
      MYSQL_DATABASE: search_zip
      MYSQL_USER: devkraken
      MYSQL_PASSWORD: DevKraken
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Docker Volumes
volumes:
  mysql_data: